fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    nfs: "https://github.com/echocat/puppet-nfs.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"

  symlinks:
    profile_nfs: "#{source_dir}"
